### ISSUE TITLE
bug: The package asks me to downgrade itself (incorrect package version set in 2.1.0 package)

### ISSUE THREAD

**Issue by vanyasem** [Mankeli-Software/dart_define#11]
### Description

For whatever reason, the CLI tools asks me to downgrade from a non-existent version

### Steps to reproduce

1. Run `dart_define` or `flutter pub run dart_define`
2. Observe
```
Update available! 2.1.1 → 2.1.0
Run dart_define update to update
```

### Free word

I have the latest 2.1.0 version. I am a first time user, and have never had the library installed before

### Platform

`dart_define: ^2.1.0`
`zsh` on macOS 13.5.2

**Comment by vanyasem** [comment]
I'd assume the issue is within [version.gen.dart](https://github.com/Mankeli-Software/dart_define/blob/main/lib/src/version.gen.dart)

**Comment by vanyasem** [comment]
By inspecting the [archive of the 2.1.0](https://pub.dev/packages/dart_define/versions/2.1.0.tar.gz) pub package it becomes apparent that `version.gen.dart` was accidentally set to 2.1.1 in the 2.1.0 release

**Comment by O-Hannonen** [comment]
Thanks for the contribution, this will be fixed within a new release!
