### ISSUE TITLE
bug: empty spaces at the end of .json files

### ISSUE THREAD

**Issue by vanyasem** [Mankeli-Software/dart_define#9]
### Description

Generated `.json` files have empty spaces at the end:

```
{
  "IP_ADDRESS": "kek",
  "FLAVOR": "dev"
}
    
```

<img width="270" alt="Screenshot 2023-09-19 at 23 11 54" src="https://github.com/Mankeli-Software/dart_define/assets/13350458/622217df-deae-404f-8425-cf5bd5307af3">

### Steps to reproduce

1. Define a configuration
2. Run the cli app `dart_define generate --json_path=build/config/dev.json --FLAVOR=dev`
3. Observe

### Platform

`dart_define: ^2.1.0`
`zsh` on macOS 13.5.2

**Comment by O-Hannonen** [comment]
Thanks for the contribution, this will be fixed within a new release!
